const PERMISSIONS = require("./permissions");

module.exports = {
  user: [
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW_OWN,
    PERMISSIONS.TICKET_COMMENT,
  ],

  agent: [
    PERMISSIONS.TICKET_VIEW_ASSIGNED,
    PERMISSIONS.TICKET_UPDATE_STATUS,
    PERMISSIONS.TICKET_COMMENT,
  ],

  admin: [
    PERMISSIONS.TICKET_VIEW_ALL,
    PERMISSIONS.TICKET_ASSIGN,
    PERMISSIONS.TICKET_UPDATE_STATUS,
    PERMISSIONS.TICKET_COMMENT,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,
  ],
};
